### ISSUE TITLE
Problems 'removing legacy naming'.

### ISSUE THREAD

**Issue by angavrilov** [cessen/cessen_rigify_ext#1]
There are two issues I see:

* The main `__init__.py` still names the feature set "Legacy Rigify Rigs" - that is what is displayed in the rigify options.
* There is a good reason for `primary_rotation_axis_legacy` - the modern rigs in Rigify define that option differently. If you look into the console, with your feature set Rigify prints a redefinition warning/error message. Unfortunately due to the design of the parameter system, the option names can conflict, so it's advised to use more rig-specific naming.

**Comment by cessen** [comment]
Ah, thank you!  I'll just rename `primary_rotation_axis` to `primary_rotation_axis_cessen`, then.

**Comment by cessen** [comment]
Fixed in ad66e661ba9c0bce9d6a53949e8767caae34683f

In the long-term, I'll probably add a sub-collection of parameters to contain all of my rig type parameters.  But this will do for now.
